### ISSUE TITLE
--tmpfs overwrites existing permissions on mountpoints

### ISSUE THREAD

**Issue by dherrendoerfer** [gotoz/runq#3]
Using `--tmpfs /tmp` seems to overwrite the permissions of an existing mount directory.

We're getting this permission set on a container when running:
`drwxr-xr-x   2 root root   60 Jun 27 19:17 tmp`

The container template has:
`drwxrwxrwt  2 root root   60 Jun 27 18:41 tmp`

**Comment by pmorjan** [comment]
It's not clear what the issue is.
- if you don't apply the `--tmpfs` parameter then there is no mount and the directory permissions are unchanged
- if you apply the parameter with no mount options  then tmpfs is mounted with default permissions
```
$ docker run --rm  --runtime runq --tmpfs /tmp alpine stat -c'%n %A' /tmp
/tmp drwxrwxrwt
```
- you can always specify mount options as described in the docker documentation: E.g.
```
$ docker run --rm  --runtime runq --tmpfs /tmp:mode=0700  alpine stat -c'%n %A' /tmp
/tmp drwx------
```
Tmpfs in runc and runq should not behave differently.

Can you please provide at least a simple example to reproduce the issue with the **current** release of runq?
Thanks.

**Comment by dherrendoerfer** [comment]
I verified it with the latest release, and it does indeed work correctly.
I'll be closing the issue.

Thanks for the help!
